site_name: OldMerkum github page
nav:
  - Home: index.md
  - Projects and misc:
    - Advantage: projects_misc/ultrablastkin.md
    - Misc: projects_misc/misc.md
  - Site Setup:
    - MkDocs: site_setup/mkdocs.md
  - Contact: contact.md

extra_css:
  - css/form.css

extra_javascript:
  - js/post_contact.js
