site_name: OldMerkum
nav:
  - Home: index.md
  - Game Projects:
    - Advantage: game_dev/advantage.md
  - Demos:
    - Advantage Demo: demos/advantage/html/advantage.html
  - Contact: contact.md

extra_css:
  - css/form.css

extra_javascript:
  - js/post_contact.js
