site_name: OldMerkum
nav:
  - Home: index.md
  - Game Projects:
    - Ultrablastkin: game_dev/ultrablastkin.md
  - Demos:
    - Ultrablastkin Demo: demos/ultrablastkin/html/ultrablastkin.html
  - Contact: contact.md

extra_css:
  - css/form.css

extra_javascript:
  - js/post_contact.js
